version: "3.9"

services:
  command:
    build: "."
    command: "command"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
      NATS_ADDRESS: "nats:4222"
  query:
    build: "."
    command: "query"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "."
    command: "pusher"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  postgres:
    build: "infrastructure/utilits/postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
  nats:
    image: "nats-streaming:latest"
    restart: "always"
  elasticsearch:
    image: "elasticsearch:7.6.0"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
  nginx:
    build: "infrastructure/nginx"
    ports:
      - "8080:80"
    depends_on:
      - "command"
      - "query"
      - "pusher"